### ISSUE TITLE
If you unregister, the register page still thinks you're an active custodian.

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#104]
```
You are currently active as an eosDAC custodian board member.
```

Is this because new pay period isn't currently called automatically?

**Comment by kasperfish** [comment]
thats because unregistering as a candidate doesn't affect you being a custodian.

**Comment by lukestokes** [comment]
Thanks for clarifying. It just seemed a little strange, but now I remember that was by design.
