### ISSUE TITLE
Can not read property of 'cpu_weight' of null

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#113]
![image](https://user-images.githubusercontent.com/344748/46377592-9bec9a00-c65e-11e8-92f1-347ad073b224.png)

Michael got this on the latest build of master for an account that only has bandwidth delegated from others.

**Comment by nanonano7** [comment]
whats the name of the account?

**Comment by nanonano7** [comment]
should be fixed
