### ISSUE TITLE
Improve the UX/UI for the API node endpoint selection 

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#15]
# Goal:

As simple and as automated as possible, while still giving more advanced features to those who want them.

## Ideas:

Vertical tabs:

1. Automatic Selection
2. Choose Endpoint

(feel free to change these tag names, this is just my initial suggestion)

### Automatic Selection

Use the code to find the fastest node and provide a single connect button. Ideally, we should make this automatic as well. Maybe a 10 second count down? That way we give them enough time to pick the "Choose Endpoint" option (pause the timer if they interact with the page), while also automatically connecting. Including a `Connect` button would allow them to connect automatically right away without waiting for the countdown also.

#### Possible language:

> Click `Connect` below to automatically connect to the fastest endpoint to your location selected from the top EOS block producers. You can also select `Choose Endpoint` to specify an endpoint. If you do not choose an endpoint before the countdown is complete, you will automatically be connected to the fastest endpoint.

### Choose Endpoint

Here we'll have a drop down box of the top BP endpoints. One of those options should be `Use a Custom Endpoint` which displays a new input field where they can specify an endpoint directly.

#### Possible language:

> Select the endpoint you would like to use and click `Connect`. Endpoints from the top block producers have been provided for you, but you can also specify your own custom endpoint by selecting `Use a Custom Endpoint`, populating the input with a url, and pressing `Connect`.

**Initial thoughts:** When they select a custom endpoint, until they put in a valid URL, the Connect button on this tab should be disabled. Once they put in a valid url, it should be enabled so they can click it.

**Comment by nanonano7** [comment]
sounds good. i will implement it now

**Comment by lukestokes** [comment]
Probably should update the settings page to match the entry page. It still shows the old layout:

![image](https://user-images.githubusercontent.com/344748/43752968-18e9020e-99c9-11e8-9327-2597e4b09fb8.png)

Can we change the tabs to match the explorer? I think it's really important to keep a consistent UX/UI and tabs across the top like this is more what I was thinking:

![image](https://user-images.githubusercontent.com/344748/43753024-64664aac-99c9-11e8-869c-333bfaa50fe4.png)

Also, when I hit escape I get this view which is really strange:

![image](https://user-images.githubusercontent.com/344748/43753047-7328c7ae-99c9-11e8-8d8c-ac0cde0b4f4e.png)

**Comment by nanonano7** [comment]
![endpoint](https://user-images.githubusercontent.com/30548940/43762367-0bf4ef40-9a28-11e8-8db0-1944ebee3048.gif)
I guess this is what you want?
What should the countdown connect button display inside the settings?
something like Connect to server with fastest connection?

**Comment by nod74** [comment]
@lukestokes I totally agree with your comments above. From the regualr User POV it does not matter from which endpoint the toolkit connects. The greymass tool uses the countdown for automatic connection too, I think they even don´t give the user the option to connect to another endpoint, only if there is an error. 
Whats the bennfit of choosing an endpoint?

**Comment by nanonano7** [comment]
a user might not trust every bp. what i get from places like reddit is that some people really dont like some BPs

**Comment by nod74** [comment]
![eos-dac-register-as-member-01](https://user-images.githubusercontent.com/3214535/43771528-d2bf98c0-9a3f-11e8-8fe1-45ecab3635d1.png)
![eos-dac-register-as-member-01-b](https://user-images.githubusercontent.com/3214535/43771529-d2da7f6e-9a3f-11e8-835c-bb0de41ee1d5.png)

**Comment by nod74** [comment]
We could even erase the left "Automatically connect to the fastest Endpoint in..." Form.  But maybe its nice to see to which endpoint you got connected automatically

**Comment by kasperfish** [comment]
implemented based on the new screens received by nod74
