### ISSUE TITLE
link to explorer instead of iframing it.

### ISSUE THREAD

**Issue by kasperfish** [eosdac/eosdactoolkit#16]
I'll crosslink the explorer to the dactools.

**Comment by nanonano7** [comment]
i would also prefer that. @lukestokes what do you think?

**Comment by lukestokes** [comment]
As I mentioned on the call, I like having the explorer built in to the eosDAC Member Client as it is now. It seems to work rather well in my initial testing. That's just my preference though, so if we want to keep it separate, that's okay too.
