### ISSUE TITLE
Add a version number display to the settings page

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#168]
As this (eventually) becomes a distributed, decentralized application, we'll need to keep track of which version people are running in order to do tech support. Let's display the package.json version number on the settings page here: https://members.eosdac.io/settings

**Comment by kasperfish** [comment]
I'll investigate how to get the version number from within package.json. if this is not possible I'll add a config variable.

**Comment by kasperfish** [comment]
![image](https://user-images.githubusercontent.com/5130772/47230712-48eb4480-d3cb-11e8-93a9-59ce144da312.png)
