### ISSUE TITLE
Idea: create a way to cast a vote for eosdacserver within the interface

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#174]
In our branding / vision / mission call today, we discussed a number of topics including how it's confusing for someone who comes to our site and wants to vote for us as a block producer. The member client relates to us as a DAC (and as a DAC, we're an EOS Block Producer). The DAC Toolkit will serve a different purpose under the DAC Chain initiative.

As such, we'd like to improve our current eosdac.io `Vote eosdacserver` call to action experience and not just send them to the graymass eos-voter github page. Instead we want to create a new page on the website explaining how to use eos-voter to vote for us and we'd like to explain how to use Scatter to vote for us. As part of that, our call to action will be to go to the member client and vote for us there. My current vision for this would be something like this:

* A single vote action only such as  "cleos system voteproducer approve <voter> eosdacserver"
* If the account already has 30 votes, not including us, show a popup of their existing votes and ask which block producer they would like to remove and replace with eosdacserver. Complete both the unapprove and approve actions in a single transaction.
* If they are already voting for us, show a message like "Thanks for supporting eosdacserver with your vote"

Potential future improvements:

* Display a list of proxies that currently vote for us and give them the option to set one of them as a proxy. Link out to existing proxy tools such as https://www.alohaeos.com/vote/proxy

Discussion points:

* Where should this action item be?
    * Should we have it as a popup around this icon? Maybe an `*` if they are a member but they haven't voted for us?
    ![image](https://user-images.githubusercontent.com/344748/47449414-2de05200-d788-11e8-8792-9853f628e783.png)
    * Should it be a main menu item on the left that goes to a whole page explaining our vision as a block producer and why we're working to earn their vote?
    * Should it be buried in the settings or maybe just on the home page for the client?
* Any concerns with vote begging?
   * I don't want people to think they have to vote for eosdacserver in order to be a member of the DAC. That is not at all true.
   * At the same time, I think it's natural to provide a tool (or support a community) and include a "Brought to you buy..." with a call to action to support the work with a vote.
* Too much confusion or too many calls to action?
  * Supporting eosdacserver is a separate concern for the DAC. It's an important one because (currently) it's the primary revenue source for the DAC, but it's still secondary to the purpose of the member client which is to engage the DAC.
  * There's a lot going on in the member client already and the amount of stuff there will only increase in the future. We don't want it to get too busy with too many calls to action.

**Comment by kasperfish** [comment]
I think this should not be a part of the member client. we can do something on eosdac.io itself though.

**Comment by lukestokes** [comment]
@kasperfish thanks for the feedback. I felt the same way since the beginning, which is why I haven't pushed for this yet. After talking through the branding and strategy for what separates "The Community Own Block Producer" from "DAC Enabler" from "We are a DAC" got me thinking a little differently. The Member Toolkit is directly a tool for managing a community owned block producer. That's what it will be used for. The DAC Toolkit will be more like a DAC Enabler tool (probably part of DAC Chain). It makes sense to me to include voting for the BP in the tool for managing that BP.

If we integrate Scatter (and in the future, other authentication methods such as Ledger Nano S, EOS Lynx, MEET.one, etc) into our website then, in my mind, that increases the attack service to include that website which means we may need to take additional security precautions for that server, that domain, etc. I think we (ideally) don't just want people to vote for us, but also to engage with our community and help us make community decisions as a DAC about how we operate as a BP. That's my current thinking, anyway.

**Comment by kasperfish** [comment]
okay I see. having the "voting portal" on the same domain makes sense because the user is already logged in with scatter (or similar). I don't think it would take that long to implement.

**Comment by lukestokes** [comment]
Oh, that's a good point. I hadn't even thought about the domain name keys related to how scatter works. Yeah, if they are already logged in, that vote would be easy.

Thoughts on the process? Instead of showing a full "vote for 30 BPs" interface, how do you think about just voting for ours? We could link out to other voting portals as one possible approach, but since this is the eosDAC Member Client and one of the responsibilities of this particular DAC is managing the eosdacserver block producer, it makes sense to just keep this super simple. We'd still allow token holders to have influence, regardless of if they vote for our BP, but making it easy to support us with their EOS stake makes sense to me.

**Comment by lukestokes** [comment]
Was testing this on dev and noticed this float is above the transaction pop-up which is strange:

<img width="1338" alt="screen shot 2018-11-14 at 3 12 52 pm" src="https://user-images.githubusercontent.com/344748/48512703-cb76f080-e81f-11e8-99e2-271f98619862.png">

The notification bar should always be above everything else.
