### ISSUE TITLE
Skin the "Sign In" Modal Window

### ISSUE THREAD

**Issue by nod74** [eosdac/eosdactoolkit#18]
Currently the SIGNIn page looks like this:
![grafik](https://user-images.githubusercontent.com/3214535/44033868-fb27dbc6-9f0b-11e8-8c8f-e15c78aa40ed.png)
Would be great If we can achieve this:
![eos-dac-sign-in-01](https://user-images.githubusercontent.com/3214535/44034032-66f4aac8-9f0c-11e8-8aee-897c32150d6b.png)

 On some point we need a dropdown anyway (ledger / trezor / ...)

**Comment by nanonano7** [comment]
should i also include the tabs and the stepper steps? not sure for what they are needed for on logging in
what are the dimensions of the modal? i would guess minWidth:50vw and minHeight: 50vh

**Comment by nod74** [comment]
As a user can have multiple eos accounts I guess he can have multiple eosdac member accounts, so in my opinion I would show the Tabs. 

What happens if the InternetConnection is interrupted, propably there is an error message "could not connect to Endpoint" or something like this, so I would show the API Endpoint "Step" in Status "green". 

Yes an additional "close" Button makes sense too. 

On Desktop I would set the max height to 610px and max width to 900px. Do you adjust the size  by viewport?
https://alligator.io/vuejs/vue-media-queries/

**Comment by nanonano7** [comment]
so you mean the tabs should also act as a stepper that gets activated when the user logs in and isnt a member?

i use the default quasar grid system with breakpoints like bootstrap.
https://quasar-framework.org/components/flex-css.html
The modal is just as big as the content that they hold. i didnt give them any size but now i can give them the ones you just gave me

**Comment by nod74** [comment]
? No Tabs should never act as a stepper, But I think the "RegisterAsaMember" Tab should always be available.

**Comment by nod74** [comment]
Looks very good nano!!! Only 3 little things. On the **Sign in** Tab (Stepper)  the "Registration Step" should not be visible. Can the Close button float right?
![grafik](https://user-images.githubusercontent.com/3214535/44137693-963a5d12-a071-11e8-807c-7c364b34b201.png)

For testing I chose Register as A Member Tab and chose the same identity then this modal came up:
![grafik](https://user-images.githubusercontent.com/3214535/44138038-e6d363a8-a072-11e8-82b8-fb36c2ba16fa.png)

Can we give the Status Message the same Padding as the other forms? And Mybe the wording in this case. "You are already registered as a eosDAC Member".

In my opinion the Login/Register Process looks super slick now!!
