### ISSUE TITLE
Double check we're handling daylight savings time correctly

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#183]
I just happened to notice it said "one hour later compared to you" until I modified my profile again. It's a minor issue, but if we ever do anything more interesting with user-specific timezones, we may want to clean that up.

**Comment by piecesnbits** [comment]
I'm not quite sure what exactly is the issue.

**Comment by piecesnbits** [comment]
@lukestokes can you please explain this issue a bit further? I don't understand what you mean.

**Comment by lukestokes** [comment]
If it can't be easily reproduced, no worries.
