### ISSUE TITLE
"Sign the Constitution Modal Window"

### ISSUE THREAD

**Issue by nod74** [eosdac/eosdactoolkit#19]
![2018-08-13 13_49_53-eosdac member client](https://user-images.githubusercontent.com/3214535/44034168-bf85d554-9f0c-11e8-8a25-164c2d08ced7.png)

If we want that the User can use the Toolkit without Signing the Const. I recommend to  show a permanent alert at the bottom of the Page like this:

![grafik](https://user-images.githubusercontent.com/3214535/44034391-486185a8-9f0d-11e8-98ff-85a813e6c333.png)

The Modal should look like this:
![eos-dac-register-as-member-03](https://user-images.githubusercontent.com/3214535/44034454-686e4d5e-9f0d-11e8-9e0b-aefba3801839.png)

**Comment by lukestokes** [comment]
I think we've got this done. Reopen if I'm incorrect.
