### ISSUE TITLE
Update the text on the candidate registration section to explain unstaking delays

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#192]
If someone hasn't been accepted as a custodian, the unstake process will take 60 minutes based on the time delayed permissions we have in place.

If they have been elected as a custodian, the full unstaking time as configured for the contract has to happen first, and then the low-level one hour delay once the transaction is submitted.

**Comment by piecesnbits** [comment]
https://github.com/eosdac/eosdactoolkit/issues/195
duplicate issue
