### ISSUE TITLE
On the custodian voting page, display the amount of EOS they are requesting as payment

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#210]
I think this is a useful metric people should be aware of when evaluating custodians. Thoughts?

**Comment by 4Ykw** [comment]
Yep, transparency should always be inline. Also, if there is any room for how the payment will be done. Let's say, every X months, Y amount, for the total amount of Z. This is something I have seen as being a "best practice on most of the blockchain community". Not necessarily EOS related.

Cheers

**Comment by lukestokes** [comment]
The payment I was referring to isn't related to worker proposals, just custodian pay which is paid out with every newperiod call which is every 7 days.

**Comment by 4Ykw** [comment]
Hummm... I see, missed the context. Is this coming from a specific DAC token sell pool? or from direct contribution?

Either way, i think it will be beneficial to show where is the payment coming from. And how much "effort" each custodian is asking for (in term of %), in comparison to others and/or if it is coming from a specific pool of "resources".

**Comment by piecesnbits** [comment]
yeah we can show that. where do you want it to go? in the candidate drop down? putting it in the header box itself will break responsiveness. suggestions?

**Comment by lukestokes** [comment]
@piecesnbits Yeah, I guess it'll have to be in the dropdown then. Thanks.

@4Ykw All DAC payments come from the DAC holdings which come from DAC revenue (currently, block production). Custodians essentially put in the same effort in that they approve or deny worker proposals. Check the white paper for details on how custodian pay works and what their responsibilities are.

**Comment by 4Ykw** [comment]
@lukestokes I read it, but to be honest, it's quite hard to understand some parts. Becomes too "lawfull wording" at some point. But now I understand thanks.
