### ISSUE TITLE
Explore additional values for the custodian json

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#28]
User Handles Like:

- Telegram
- Discord
- WeChat

Nickname

**Comment by michaeljyeates** [comment]
https://schema.org/ContactPoint seems to be the best option for this

it is attached to a Person object via the contactPoint property

productSupported can be text so we can just put 'telegram' there

**Comment by lukestokes** [comment]
Interesting. So we can use ContactPoints, right?

> ContactPoint | A contact point for a person or organization. Supersedes contactPoints.

productSupported makes sense.

Where should we put the actual value of the username? Would that be the `identifier` just used as text or should we go with `name` since ContactPoint extends Things?

**Comment by piecesnbits** [comment]
please reopen when you want to discuss thus further. Closing because inactive.
