### ISSUE TITLE
Can't scroll within modal window using a mouse click

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#32]
![image](https://user-images.githubusercontent.com/344748/44277536-a965d600-a210-11e8-88e9-f665d906bd9b.png)

When I try to click and drag the bar on the far right, nothing happens. I'm so used to using my track pad two-finger scroll that I didn't notice an issue before.

**Comment by lukestokes** [comment]
The strange thing is, once I use the two finger scroll from the track pad, then I can click the scroll bar and it starts working. Odd.

**Comment by nanonano7** [comment]
my scroll bar looks different 
![image](https://user-images.githubusercontent.com/30548940/44299754-55382000-a2fc-11e8-9d34-b49a4f998648.png)

**Comment by lukestokes** [comment]
Are you on a Mac using Chrome? Anyone else testing in Chrome on a Mac? It's difficult to click and only works some of the time. Maybe there's some other overlay issue causing this.

**Comment by nanonano7** [comment]
its hard to test for me since im on linux but i found this.
https://stackoverflow.com/questions/7855590/preventing-scroll-bars-from-being-hidden-for-macos-trackpad-users-in-webkit-blin

**Comment by lukestokes** [comment]
Ah, interesting. As long as this doesn't become a problem for people who don't know how to scroll with a trackpad, I guess we're okay. I'll leave it to you all as to if we need to make a change or not.

**Comment by lukestokes** [comment]
I guess we'll close this for now and re-open if it becomes an issue after testing/launch.
