### ISSUE TITLE
Update Ricardian Contract for EOS token transfer

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#34]
![image](https://user-images.githubusercontent.com/344748/44278452-9f91a200-a213-11e8-9d6f-2fc765a4a878.png)

It should use this, I think: https://github.com/EOS-Mainnet/governance/blob/master/eosio.token/eosio.token-transfer-rc.md

That's what I see in Greymass.

**Comment by nanonano7** [comment]
figured out whats wrong im on it
