### ISSUE TITLE
Link 'not registered' to the same dialog as 'sign the constitution'

### ISSUE THREAD

**Issue by michaeljyeates** [eosdac/eosdactoolkit#40]
When a member is not registered the member client shows a blue bar on the bottom of the page, the bottom of a page is often the source of ui bugs so can we add the same link to 'not registered' as a fallback

**Comment by nanonano7** [comment]
yes. i think it doesnt hurt so i will add it

**Comment by nanonano7** [comment]
![image](https://user-images.githubusercontent.com/30548940/44301545-1369a280-a319-11e8-90e4-575d4f8d5d8f.png)
is that ok?

**Comment by michaeljyeates** [comment]
yes thanks
