### ISSUE TITLE
Fullscreen constitution is unreadable

### ISSUE THREAD

**Issue by michaeljyeates** [eosdac/eosdactoolkit#42]
When opening the constitution in fullscreen (when registering) the text is unreadable

**Comment by michaeljyeates** [comment]
<img width="973" alt="screen shot 2018-08-18 at 16 32 42" src="https://user-images.githubusercontent.com/4223666/44300849-515ccb80-a305-11e8-8ac8-214273156a18.png">

**Comment by nanonano7** [comment]
ah seems like the constitution component set the style for tables globally
