### ISSUE TITLE
the wallet should use one method to do both eos and eosdac token transfers

### ISSUE THREAD

**Issue by kasperfish** [eosdac/eosdactoolkit#46]
this can be done by loading eosio.token contract and then call transfer. just like it can be done with other contracts. no need for separate methods. for this to work the contract name should be passed to the store api https://github.com/eosdac/eosdactoolkit/issues/45

**Comment by lukestokes** [comment]
@kasperfish is this now complete?

**Comment by kasperfish** [comment]
yes it's fixed.https://github.com/eosdac/eosdactoolkit/commit/56c9c8ab21d8c27336d3f47c36fe7011567929b9
