### ISSUE TITLE
The "X" to the right of the logo and title looks strange. Can we try something different?

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#55]
![image](https://user-images.githubusercontent.com/344748/44538205-4cfa2f00-a6c6-11e8-894c-f6d03bdaac57.png)

**Comment by lukestokes** [comment]
Looks good to me! (though the google drive image looks a little funky, I assume it's just a rough draft of the logo):

![image](https://user-images.githubusercontent.com/344748/44588417-4a0d4600-a77b-11e8-8e1f-38ca7ac93f81.png)

**Comment by nod74** [comment]
I just checked, thats the preview of google drive. When I open the file it looks like this:
![grafik](https://user-images.githubusercontent.com/3214535/44588622-84e09f80-a7b6-11e8-85c0-27598d2854a5.png)
So should be all OK!

**Comment by kasperfish** [comment]
do I need to change this?
