### ISSUE TITLE
Check if icon-type-12 is missing? The external indicator for the explorer link is no longer there.

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#57]
![image](https://user-images.githubusercontent.com/344748/44539691-7b7a0900-a6ca-11e8-98fa-f524e60cfe27.png)

I'm trying to find where this change was made in the icon set or css, but I'm not understanding how it all comes together.

**Comment by nanonano7** [comment]
the icon was renamed to "transfer-out". i will add it again
