### ISSUE TITLE
Change the Member Status field if they have 0 EOSDAC tokens

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#58]
![image](https://user-images.githubusercontent.com/344748/44541554-ef6ae000-a6cf-11e8-871e-72091843b78c.png)

Maybe if the local token balance is = 0 we can show "Pending" in a blue color? Maybe we could have a mouse-over tooltip which explains you need to have some EOSDAC tokens to be a full registered member according to the constitution.

Sound good?

**Comment by kasperfish** [comment]
implemented this.
