### ISSUE TITLE
Set correct Icons

### ISSUE THREAD

**Issue by nod74** [eosdac/eosdactoolkit#64]
I updated the Icon font to V1.4 please check attached Screens
![grafik](https://user-images.githubusercontent.com/3214535/44584714-231a3880-a7aa-11e8-8b37-7ad1e851f328.png)

**Comment by lukestokes** [comment]
I thought I could do this, but I'm not clear on how we add icons. @nanonano7 @kasperfish is there some documentation you could add to the readme about this?
