### ISSUE TITLE
Remove double confirmations

### ISSUE THREAD

**Issue by michaeljyeates** [eosdac/eosdactoolkit#70]
Its a bad user experience to force them to click through 2 different popups (our popup and then the scatter popup)

Please remove the popup when an action is performed.  Currently the voting popup is very confusing and it doesn't even include terms and conditions, when it says it does

**Comment by lukestokes** [comment]
This was already done on DEV. Check the User Settings.

**Comment by michaeljyeates** [comment]
http://members-dev.eosdac.io/ still has it, can you check its not a regression

**Comment by michaeljyeates** [comment]
I think it is, just updated that from dev and its still there

**Comment by lukestokes** [comment]
Odd. Seems to work for me. Reload and double check your settings maybe? Here's what I see (voting_demo.mov): https://drive.google.com/drive/folders/1-TMQLaftGPgrB6YD_WHTkwYqyU2UIUrx

**Comment by kasperfish** [comment]
yest i implemented it with default "yes" because I feel that it is useful. and also because it shows that we care. for me personal the popup is not needed so I can switch it off. others might need more time for that.
