### ISSUE TITLE
adjust font-sizes

### ISSUE THREAD

**Issue by nod74** [eosdac/eosdactoolkit#74]
Hi Nano, hi kas, could we adjust the fontsizes all over the client so we have an balanced look all over the categories. Sorry my fault that I did not provided the sizes eralier...
![wallet](https://user-images.githubusercontent.com/3214535/44652859-631d2d80-a9ed-11e8-9c62-2906b4b27cb0.png)
![settings](https://user-images.githubusercontent.com/3214535/44652866-69aba500-a9ed-11e8-8e75-7d4f66cbbf86.png)
![profile](https://user-images.githubusercontent.com/3214535/44652872-6ca69580-a9ed-11e8-8058-fd937ebfb8e0.png)
![voting](https://user-images.githubusercontent.com/3214535/44652874-6f08ef80-a9ed-11e8-8b0f-f8a8e0fe1e1c.png)

**Comment by piecesnbits** [comment]
if this is still an issue please reopen.
