### ISSUE TITLE
register notification banner overlaps modal on some screen sizes

### ISSUE THREAD

**Issue by nanonano7** [eosdac/eosdactoolkit#77]
![image](https://user-images.githubusercontent.com/30548940/44956053-fbb81f80-aebd-11e8-98d3-38713ab951a2.png)

i think it might better to show the banner inside the the page layout.
we also have enough member status indications in the ui so that it cant be missed
the banner position should only be used for action related feedback imo.
the bad connection banner should also be moved to a different location (will open another issue for that)
@nod74 what do you think?

**Comment by nanonano7** [comment]
i removed the z-top class which stays under the modal now but it still lays on top of some other stuff like the send tokens button inside the wallet.
so i guess we should make it dismissable or move it inside the page layout as suggested above

**Comment by nod74** [comment]
Dismissable for sure, do we have a “jump“ in the page once the blue info shows on the top? If not i am good with the top position!

**Comment by nanonano7** [comment]
![banner](https://user-images.githubusercontent.com/30548940/44960422-d8ae5f80-aeff-11e8-844d-bf094edcd0d7.gif)
not sure what you mean with jump. this is how i would make it.

**Comment by nod74** [comment]
Top!
