### ISSUE TITLE
add resource staking/allocation to wallet

### ISSUE THREAD

**Issue by nanonano7** [eosdac/eosdactoolkit#79]
makes sense to have that.
i would put the trigger on the menu button in the right corner on those things
![image](https://user-images.githubusercontent.com/30548940/44960492-fdef9d80-af00-11e8-90db-2cafe20a66d6.png)

**Comment by nod74** [comment]
Yes!

**Comment by nod74** [comment]
Maybe we could just scale the tile a bit (vertical) once pressed on "stake/unstake in the top right corner" and fade in the action buttons. A Scaling of the slider button would be nice to. Something like this: 
![grafik](https://user-images.githubusercontent.com/3214535/44994342-7bb5b680-af9e-11e8-8b94-db4bc5f9b7e0.png)

**Comment by nanonano7** [comment]
![ram](https://user-images.githubusercontent.com/30548940/45234508-3d8a0100-b2d6-11e8-8e52-161dc3dd47f3.gif)
this is what i got so far

**Comment by lukestokes** [comment]
That looks fantastic! We should also add a tooltip when mousing over the configuration button so people know what it does.

**Comment by nod74** [comment]
I agee to both tooltips, in general I think we should add these anywhere plus if it is possible z-index / open over content. For the rest, just cosmetics I'll add a screen. Overall, nice implementation!

**Comment by nanonano7** [comment]
![ram2](https://user-images.githubusercontent.com/30548940/45268767-17a15f80-b482-11e8-80a5-1d83478e354f.gif)
added your suggestions.
should work but couldnt test it because jungle seems to be having problems

**Comment by nod74** [comment]
Hi nano, looks nice, I would suggest the following regarding the Layout:
![04 eos-dac-wallet-ram-buy-sell-v1-0](https://user-images.githubusercontent.com/3214535/45292991-2f66fb00-b4f7-11e8-9f9c-b5dabd39c3eb.png)
