### ISSUE TITLE
add addressbook for wallet

### ISSUE THREAD

**Issue by nanonano7** [eosdac/eosdactoolkit#80]
was left out in the last release
maybe with an action sheet like this
![addressbook](https://user-images.githubusercontent.com/30548940/44960584-7014b200-af02-11e8-8b6c-89a546c6050f.gif)

**Comment by nod74** [comment]
Do you need a Screen for that?

**Comment by nanonano7** [comment]
![addressbook2](https://user-images.githubusercontent.com/30548940/45052091-1806b880-b086-11e8-9a7e-1763b4587831.gif)
i think a automplete is a better option. when its empty it returns all contacts.
the manage addressbook button would open a modal where you can remove contacts

**Comment by kasperfish** [comment]
I like it!
