### ISSUE TITLE
Identify elected custodians

### ISSUE THREAD

**Issue by michaeljyeates** [eosdac/eosdactoolkit#82]
Need a way to identify the currently elected custodians in the list, it would always be the first 12 but lets make it clearer

**Comment by kasperfish** [comment]
i've added a star to the top 12
![image](https://user-images.githubusercontent.com/5130772/45601239-159f4980-ba0a-11e8-8f7f-7eec4bf49ba8.png)

**Comment by kasperfish** [comment]
atm the starts are added just to the top 12... I don't think these will always be the custodians. it will be most of the time the next custodians... we need probably an other way to display the custodians
