### ISSUE TITLE
Check dacelections -> stprofileuns for correct ricardian contract display

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#94]
![image](https://user-images.githubusercontent.com/344748/45782040-5d4eec80-bc27-11e8-997e-d38babd9a1ae.png)

Message should be:
```
An authenticated action to update the user's profile. ##Warning: This action will store the content on the chain in the history logs and the data cannot be deleted later.
```

**Comment by nanonano7** [comment]
the ricardian texts on dacelections have a different format.
so either we change the texts to be in the same format as the tokencontract or i could maybe write somtehing to deal with this format

**Comment by nanonano7** [comment]
an issue on the dacelections contract was already opened so i guess we can close this
