### ISSUE TITLE
Fix default values in newsletter subscribe on logged out index

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#95]
![image](https://user-images.githubusercontent.com/344748/45848143-feef4000-bcf2-11e8-8b6b-8aa353c14dad.png)

**Comment by kasperfish** [comment]
hey luke, yeah this is also testing... I posted a message in discord about that...

**Comment by lukestokes** [comment]
Yeah, seems the CORS isn't set yet.

![image](https://user-images.githubusercontent.com/344748/45848960-f51b0c00-bcf5-11e8-90de-6007520afe41.png)

That said, we can fix this part up as we work on that part also. :)

Hopefully the form will allow us to send blank values for the name and country. I updated the language to use the same drop down we have (mostly) for the settings page, but adjusted the values to fit what I see on the website form.

**Comment by kasperfish** [comment]
we need the cors headers fixed on the main domain...

**Comment by kasperfish** [comment]
fixed with custom backend implementation
