### ISSUE TITLE
Social links should include mouse over or location bar updates to show where they go

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoolkit#97]
No way to know where these links go:

![image](https://user-images.githubusercontent.com/344748/45920650-2702ae80-be6d-11e8-9eaa-ae79bea01d75.png)

But the main website link works correctly and displays a location:

![image](https://user-images.githubusercontent.com/344748/45920662-59aca700-be6d-11e8-9752-5a39048c8dad.png)

**Comment by lukestokes** [comment]
Looks like we're using onclick instead of a normal link, so we'll have to do something tricky:
```
    <q-btn v-if="social.link!=''" v-for="(social, i) in parseLinks"  class="on-left" :key ="i" round color="dark" @click.native="openURL(social.link)" >
      <q-icon  :name="'icon-'+social.icon" />
    </q-btn>
```
Could we just make these links with the icons inside? Would that work?

**Comment by kasperfish** [comment]
fixed
