### ISSUE TITLE
eosdac/eosdactoolkit: b91f835 (Vietnamese translation)

### ISSUE THREAD

**Issue by eosdacvietnam** [eosdac/eosdactoolkit#99]
export default {
  constitution: {
    loading_constitution: 'Đang tải Hiến Pháp',
  },
  default: {
    account_name: 'Tên Tài Khoản',
    constitution: 'Hiến Pháp',
    custodians: 'Người Giám Hộ',
    log_in: 'Đăng Nhập',
    log_out: 'Đăng Xuất',
    logged_in: 'Đã Đăng Nhập',
    logged_out: 'Đã Đăng Xuất',
    member_client: 'Bộ Công Cụ Thành Viên',
    member_status: 'Trạng Thái Thành Viên',
    menu: 'Menu',
    not_registered: 'chưa đăng ký',
    profile: 'Hồ Sơ',
    registered: 'Đã đăng ký',
    settings: 'Cài Đặt',
    sign_the_constitution: 'Ký Hiến Pháp',
    status: 'Trạng Thái',
    token_explorer: 'Tra Cứu Token',
    wallet: 'Ví',
    worker_proposals: 'Đề Xuất Công Việc',
    you_have_not_yet_registered: 'Bạn chưa là Thành Viên. Vui lòng ký hiến pháp để sử dụng Bộ Công Cụ Thành Viên.',
    your_token_balance: 'Số Dư {tokenName}',
  },
  four_zero_four: {
    go_back: 'Quay trở lại',
    sorry_nothing_here: 'Xin lỗi, không có gì cả...',
  },
  initialize: {
    authentication_method: 'Cách Thức Xác Nhận',
    connect_with_scatter: 'Kết nối với Scatter',
    identity_request_denied: 'Không xác minh được. Vui lòng thử lại và chấp nhận yêu cầu',
    import_private_keys: 'Nhập private keys',
    loading_text: 'đang tải...',
    scatter_is_locked: 'Scatter bị khóa. Vui lòng mở khóa để tiếp tục',
    scatter_not_available: 'Scatter không có. Nếu bạn đã cài Scatter, vui lòng thử lại.',
    waiting_for_scatter: 'Đang chờ Scatter...',
  },
  multi_modal: {
    register_as_dac_member: 'ĐĂNG KÝ THÀNH VIÊN DAC',
    registration: 'Đăng Ký',
    sign_in: 'ĐĂNG NHẬP',
  },
  nodeselector: {
    automatic_connection: 'Tự Động Kết Nối',
    choose_endpoint: 'Chọn Điểm Kết Nối Trong Danh Sách',
    click_connect_below: 'Ấn <b>Kết Nối</b> bên dưới để tự động kết nối vào điểm kết nối nhanh nhất theo vị trí của bạn từ các nhà sản xuất block EOS hàng đầu.',
    connect: 'Kết Nối,
    connecting: 'Đang kết nối...',
    custom_endpoint: 'Tùy Chọn Điểm Kết Nối',
    endpoint_set: 'Cài đặt điểm kết nối thành công',
    error_chain_id: 'ID chuỗi từ điểm kết nối không chính xác.',
    error_could_not_connect_to_endpoint: 'Không thể kết nối.',
    error_endpoint_connection_timed_out: 'Hết thời gian kết nối.',
    error_invalid_url: 'URL không hợp lệ.',
    gathering_endpoints: 'Đang thu thập các điểm kết nối...',
    manual_connection: 'Kết Nối Thủ Công',
    select_endpoint: 'Lựa Chọn Điểm Kết Nối từ Danh Sách',
    select_the_endpoint_you_would_like: 'Chọn điểm kết nối bạn muốn dùng và ấn <b>Kết Nối</b>. Các điểm kết nối của các nhà sản xuất block hàng đầu được liệt kê cho bạn, tuy nhiên bạn có thể tự chỉ định điểm kết nối của riêng mình bằng cách nhập vào url, và ấn <b>Kết Nối</b>.',
    specify_your_own: 'Chỉ định điểm kết nối của riêng bạn bằng cách nhập url và ấn nút kết nối.',
  },
  profile: {
    about_me: 'Tự Giới Thiệu',
    email_address: 'Địa Chỉ Email',
    familyName: 'Họ',
    female: 'Nữ',
    gender: 'Giới Tính',
    givenName: 'Tên',
    male: 'Nam',
    other: 'Khác',
    placeholder_short_bio: 'Giới thiệu ngắn gọn...',
    profile_picture_url: 'Url ảnh',
    save: 'Lưu Lại',
    social_link: 'Liên Kết Xã Hội',
    social_profile_link: 'Liên kết hồ sơ',
    website: 'Website',
  },
  lang_selector: {
    choose_your_language: 'Lựa chọn Ngôn Ngũ',
    languages: {
        chinese: 'Trung Quốc (Giản thể)',
        english_gb: 'Anh (Anh)',
        english_us: 'Anh (Mỹ)',
        french: 'Pháp',
        german: 'Đức',
        italian: 'Ý',
        japanese: 'Nhật',
        korean: 'Hàn Quốc',
        russian: 'Nga',
        spanish: 'Tây Ban Nha',
    },
  },
  register: {
    already_registered: 'Bạn đã đăng ký Thành Viên eosDAC.',
    checking_status: 'Kiểm tra trạng thái thành viên...',
    close: 'Đóng',
    congratulations_registered: 'Chúc mừng! Bây giờ bạn đã là Thành Viên eosDAC.',
    constitution_hash: 'Hash Hiến Pháp',
    could_not_retrieve_member_status: 'Không thể kiểm tra trạng thái thành viên',
    fullscreen: 'Toàn Màn Hình',
    i_accept_the_constitution: 'Tôi đồng ý với Hiến Pháp',
    loading_latest_constitution: 'Đang tải Hiến Pháp...',
    must_sign_constitution: 'Để trở thành Thành Viên của eosDAC, bạn phải đồng ý và ký Hiến Pháp.',
    register: 'Đăng Ký',
    registration_sign_the_constitution: 'Đăng Ký - Ký Hiến Pháp',
    try_again: 'Thử Lại',
    updated_constitution: 'Hiến pháp được cập nhật. Vui lòng ký hiến pháp để tiếp tục.',
  },
  scatter_signin: {
    choose_authentication_type: 'Vui lòng chọn cách thức xác nhận để đăng nhập Bộ Công Cụ Thành Viên eosDAC.',
    choose_connection_type: 'Chọn Loại Kết Nối',
    connection_type: 'Loại Kết Nối',
    identity_request_denied: 'Không xác minh được. Vui lòng thử lại và chấp nhận yêu cầu.',
    scatter_is_locked: 'Scatter is locked. Please unlock to continue.',
    scatter_is_not_available: 'Scatter không có. Nếu bạn đã cài Scatter, vui lòng thử lại hoặc vào Permissions, xóa permission cho trang này, và thử lại.',
    sign_in: 'ĐĂNG NHẬP',
    waiting_for_scatter: 'Đang chờ scatter...',
  },
  scatter_tutorial: {
    if_you_are_unable_to_choose_an_identity: 'Nếu bạn không thể xác minh, vui lòng làm theo các bước dưới đây.',
    import_account: '1. Import account',
    import_account_into_identity: '2. Import Account into Identity',
    import_identity_instructions: 'Vào mục Identities.<br>Trong mục Identity ấn nút hình cây bút.<br>Sau đó, vào mục "Account".<br>Bây giờ lựa chọn tài khoản nhập vào từ danh sách.<br>Lưu lại Identity của bạn với nút Save bên góc phải trên cùng.',
    make_sure_active_key: 'Đảm bảo rằng bạn nhập active key cho tài khoản nhập vào scatter.',
    permissions: '1. Vào Permissions',
    revoke_identity: '3. Thu hồi Identity',
    select_domain: '2. Chọn Domain',
    unable_to_connect: 'Nếu bạn không thể kết nối với Scatter, làm các bước dưới đây để reset permissions của bạn.',
  },
  settings: {
    API: 'API',
    API_endpoint: 'API Endpoint',
    click_below_to_unregister_membership: 'Ấn vào nút bên dưới để hủy tư cách thành viên eosDAC',
    click_register_now: 'Ấn "Đăng Ký Ngay" để trở thành thành viên eosDAC.',
    current_connection: 'Kết Nối Hiện Tại',
    current_language: 'Ngôn Ngữ Hiện Tại',
    current_status: 'Trạng Thái Hiện Tại',
    member_status: 'Trạng Thái Thành Viên',
    language_preference: 'Ngôn Ngữ Ưu Tiên',
    NOT_REGISTERED: 'CHƯA ĐĂNG KÝ',
    register_as_member: 'Đăng ký Thành Viên',
    register_now: 'Đăng Ký Ngay',
    REGISTERED: 'ĐÃ ĐĂNG KÝ',
    settings: 'Cài Đặt',
    unregister_membership: 'Hủy Tư Cách Thành Viên',
  },
  transaction: {
    action: 'Thực Hiện',
    by_completing_agree: 'Bằng cách hoàn tất giao dịch này, tôi đồng ý với các điều khoản sau đây.',
    cancel: 'Hủy Bỏ',
    fields: 'Fields',
    from: 'Từ',
    loading_abi: 'Đang tải ABI...',
    memo: 'Memo',
    pushing_transaction: 'Tiến Tới Giao Dịch...',
    quantity: 'Số Lượng',
    to: 'Đến',
    transaction: 'Giao Dịch',
    transaction_successful: 'Giao Dịch Thành Công',
    view_in_explorer: 'Tra cứu giao dịch',
    warning_bandwidth: 'Network Bandwidth Thấp. Network bandwidth của bạn còn ít hơn 10%. Giao dịch có thể không hoàn thành.',
    warning_cpu: 'CPU Thấp. CPU của bạn còn ít hơn 10%. Giao dịch có thể không hoàn thành.',
    warning_ram: 'RAM Thấp. RAM của bạn còn ít hơn 10%. Giao dịch có thể không hoàn thành.',
    warning_ricardian: 'Hợp đồng ricardian cho hoạt động này không tìm thấy. Bạn có chắc là muốn thực hiện giao dịch này?',
  },
  wallet: {
    amount: 'Số Lượng',
    CPU: 'CPU',
    history: 'Lịch Sử',
    memo: 'Memo',
    network: 'Network',
    RAM: 'RAM',
    settings: 'Cài Đặt',
    transfer: 'Giao Dịch',
    transfer_to: 'Chuyển đến',
    transfer_tokens: 'Chuyển Tokens',
    wallet: 'Wallet',
    total_staked: 'Tổng Đặt Cọc',
    send_tokens: 'Chuyển Tokens',
    total_eos_balance: 'Tổng số dư eos',
    liquid: 'tiền mặt',
    token_selection_and_quantity: 'Chọn Token và Số Lượng',
    select_token_to_send: 'Chọn Token để chuyển',
    select_from_list: 'Lựa Chọn từ Danh Sách',
    quantity_to_send: 'Số Lượng để chuyển',
    destination: 'Điểm Đến',
    manage_addressbook: 'Quản Lý Sổ Địa Chỉ',
    or_select_address_book: 'Hoặc lựa chọn Tài Khoản Nhận từ Sổ Địa Chỉ',
    input_a_destination_account: 'Nhập Tài Khoản Nhận',
    total: 'tổng'
  },
  wp_member_view: {
    approx_USD: '(Aprox. xxxx USD)',
    deadline: 'Hạn Chót',
    no: 'No',
    requested_payment: 'Thanh Toán Được Yêu Cầu',
    submitted: 'Đã Nộp',
    time_left: 'Thời Gian Còn Lại',
    type: 'Loại',
    view_proposal: 'Xem Đề Xuất',
    view_votes: 'Xem Phiếu Bầu',
    votes: 'Phiếu Bầu',
    worker_proposal_by: 'Đề Xuất Công Việc bởi',
    yes: 'Đồng Ý',
  },
  worker_proposals: {
    APPROVED: 'ĐÃ DUYỆT',
    OPEN: 'ĐANG MỞ',
  },
  vote_custodians:{
    loading_candidates: 'Đang tải các ứng viên',
    candidate_list: 'Danh Sách Ứng Viên',
    my_votes: 'Phiếu Bầu Của Tôi',
    submit_my_votes: 'Bỏ Phiếu',
    description_main: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam libero urna, efficitur at laoreet fermentum, facilisis in ex. Proin luctus erat sem, ut mollis dui laoreet id. Curabitur eleifend ante in lacus rutrum dapibus. Nulla sit amet maximus metus, ac interdum dui. Aliquam placerat nisl eu bibendum dictum. Integer pharetra diam pretium felis venenatis, in aliquam ex imperdiet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    description_side: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam libero urna, efficitur at laoreet fermentum, facilisis in ex. Proin luctus erat sem, ut mollis dui laoreet id.',

  }
}

**Comment by lukestokes** [comment]
Fantastic! Thank you @eosdacvietnam. I added it to the system, but it does need some additional language strings translated which were added after you did this translation. You can see the english here: https://github.com/eosdac/eosdactoolkit/commit/71a3081e8d68c68d7c9aeda2b907440d22cbfd4b

**Comment by eosdacvietnam** [comment]
Thank you, Luke. I will finish it as soon as possible.
